config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :courses

  root 'courses#index'

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  get 'signout' => 'sessions#destroy'
  

end

app/models/course.rb
class Course < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :user_name, presence: true, uniqueness: true
  validates :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= session[:user_id] && User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(courses_params)
    if @course.save
      redirect_to root_path, :notice => "Course was successfully created."
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(courses_params)
      redirect_to root_path, :notice => "Course was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to root_path
  end

  private

  def courses_params
    params.require(:course).permit(:title, :day)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_user_name(params[:user_name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "User was successfully logged in."
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "User was successfully logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "User was successfully created."
    else
      redirect_to new_user_path, :notice => "User was not successfully created."
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(users_params)
      redirect_to root_path, :notice => "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, :notice => "User was successfully deleted."
  end

  private

  def users_params
    params.require(:user).permit(:user_name, :password, :about)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label 'Day course?' %>
  <%= f.check_box :day %>
  <br>
  <%= f.submit %>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit course: </h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1> Courses: </h1>
<h3><%= link_to 'New Course', new_course_path %></h3>
<table>
  <tr>
    <th>Title</th>
    <th>Day or Night</th>
  </tr>

    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.title, course_path(course) %></td>
        <% if course.day %>
          <td>Day</td>
        <% else %>
          <td>Night</td>
        <% end %>
        <td><%= link_to 'Delete', course, method: :delete%></td>
      </tr>
    <% end %>
</table>

app/views/courses/new.html.erb
<h1>New Course: </h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1><%= @course.title %></h1>
<br>
<h3>Day course or night course: </h3>
<% if @course.day %>
  <p>Day</p>
<% else %>
  <p>Night</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DanielHarrisWeek7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to 'Home', root_path %>
  |
  <% if current_user %>
    <%= current_user.user_name %>
    |
    <%= link_to 'Signout', signout_path %>
  <% else %>
    <%= link_to 'New User', new_user_path %>
    |
    <%= link_to 'Signin', signin_path %>
  <% end %>
  <br>
  <br>
  <% if notice %>
    <%= notice %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :about %>
  <%= f.text_field :about %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User:</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <tr>
    <th>User Name: </th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.user_name, user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_for @user do |f| %>

  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <br>
  <%= f.label :password %>
  <%= f.label :password %>
  <br>
  <%= f.label :about %>
  <%= f.text_field :about %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.user_name %></h1>
<br>
<p><%= @user.about %></p>